export const profile = {
  name: "岑斯恬",
  nameEn: "CEN SITIAN",
  role: "Product / Visual / AI Designer",
  location: "Hangzhou · Hong Kong",
  phone: "+86 152 1954 8467",
  email: "mountaincen@qq.com",
  wechat: "cstis666",
  cargo: "cendesign.cargo.site",
  xhsId: "youshan666",
  xhs: "https://www.xiaohongshu.com/user/profile/5b63e9bff7e8b95dbec5c46d",
  linkedin: "https://www.linkedin.com/in/%E6%96%AF%E6%81%AC-%E5%B2%91-109b65385/",
  github: "https://github.com/TinaCEN?tab=repositories",
};

export const intro = {
  portrait: "/portrait-sq.jpg",
  frame: "/polaroid-frame.png?v=2",
  sign: "/signature.png",
  caption: "Tina CEN",
  lead: ["探索aigc与HCI的边界", "把商业逻辑和用户情感转化为有温度的设计"],
  experience: "现任职淘宝闪购，曾实习于微信支付与欧诗漫，参与亿级产品的体验落地。",
  marks: ["淘宝闪购", "微信支付", "欧诗漫"],
};

export const contents = [
  {
    no: "01",
    title: "UI / UX Design",
    keyword: "PRODUCT",
    cover: "/toc/product-10.jpg",
    previews: [
      "/toc/product-01.jpg",
      "/toc/product-02.jpg",
      "/toc/product-03.jpg",
      "/toc/product-04.jpg",
      "/toc/product-05.jpg",
      "/toc/product-06.jpg",
      "/toc/product-07.jpg",
      "/toc/product-08.jpg",
      "/toc/product-09.jpg",
      "/toc/product-10.jpg",
      "/toc/product-11.jpg",
    ],
    filter: "product",
  },
  {
    no: "02",
    title: "Brand Identity",
    keyword: "IDENTITY",
    cover: "/toc/brand-08.jpg",
    previews: [
      "/toc/brand-01.jpg",
      "/toc/brand-02.jpg",
      "/toc/brand-03.jpg",
      "/toc/brand-04.jpg",
      "/toc/brand-05.jpg",
      "/toc/brand-06.jpg",
      "/toc/brand-07.jpg",
      "/toc/brand-08.jpg",
      "/toc/brand-09.jpg",
    ],
    filter: "branding",
  },
  {
    no: "03",
    title: "Visual Design",
    keyword: "CAMPAIGN",
    cover: "/toc/visual-01.jpg",
    previews: [
      "/toc/visual-01.jpg",
      "/toc/visual-02.jpg",
      "/toc/visual-03.jpg",
      "/toc/visual-04.jpg",
      "/toc/visual-05.jpg",
      "/toc/visual-06.jpg",
      "/toc/visual-07.jpg",
      "/toc/visual-08.jpg",
      "/toc/visual-09.jpg",
      "/toc/visual-10.jpg",
    ],
    filter: "branding",
  },
  {
    no: "04",
    title: "AI Creative",
    keyword: "GENERATE",
    cover: "/toc/ai-01.jpg",
    previews: [
      "/toc/ai-01.jpg",
      "/toc/ai-02.jpg",
      "/toc/ai-03.jpg",
      "/toc/ai-04.jpg",
      "/toc/ai-05.jpg",
    ],
    filter: "ai",
  },
];

export const about = {
  lead: "把策略、情绪和人工智能放在同一张工作台上——做能被用起来的产品，也做能被记住的视觉。",
  body: [
    [
      "视觉传达背景×交互体验设计，探索AIGC与人机交互的边界，致力于将商业逻辑与用户情感转化为有温度的设计。",
      "曾实习于腾讯微信支付与国民品牌欧诗漫电商视觉设计，参与亿级产品的体验设计落地。",
      "现职阿里巴巴淘宝闪购体验AI设计师，深耕即时零售AI导购与搜推体验设计。",
    ],
    [
      "毕业于中国美术学院视觉设计专业，现就读于香港理工大学交互设计学硕士（QS50）。",
      "擅长AI驱动工作流程进行原型开发，作品参加 2026年苹果教育AI展览。",
      "曾获阿里巴巴D20未来青年传播奖、腾讯AIGC MV金奖、KTK品牌设计奖与新浪潮数字艺术设计奖。",
    ],
  ],
  education: [
    { school: "香港理工大学", detail: "创新多媒体娱乐硕士 · MScIME", time: "2025.09 — 2027.03" },
    { school: "中国美术学院", detail: "视觉传达设计 · 本科", time: "2021.09 — 2025.06" },
  ],
  experience: [
    { company: "阿里巴巴 · 淘宝闪购", detail: "AI体验设计", time: "2026 — 至今" },
    { company: "腾讯 · 微信支付", detail: "视觉设计", time: "2025.12 — 2026.05" },
    { company: "欧诗漫", detail: "视觉设计", time: "2025.06 — 2025.08" },
  ],
};

const p = (n) => `/work/${String(n).padStart(2, "0")}.jpg`;
const range = (from, to) => Array.from({ length: to - from + 1 }, (_, i) => from + i);
const rangeSkip = (from, to, skip) => range(from, to).filter((n) => n !== skip);

export const projects = [
  {
    slug: "taobao-flashbuy",
    title: "淘宝闪购｜AI创新导购产品",
    titleEn: "Taobao Flash Buy",
    year: "2026",
    client: "阿里巴巴",
    category: "product",
    tags: ["产品设计", "AI 导购", "交互"],
    cover: "/covers/taobao-flashbuy.jpg",
    locked: true,
    password: "666",
    excerpt: "把购物入口从「人找商品」改写成「商品找人」——用场景、时间和天气驱动的 AI 导购时刻。",
    description:
      "在淘宝闪购 intern / AI 产品岗位中，围绕即时零售做「闪购时刻」：冷启动文案、场景识别与对话式导购。设计策略层把被动搜索改成主动预测，让 AI 在对的时间把一顿饭、一场局推到用户面前。",
    pages: range(5, 9),
  },
  {
    slug: "weixin-treat",
    title: "微信支付 · 求请客",
    titleEn: "Weixin Pay Treat",
    year: "2026",
    client: "腾讯",
    category: "product",
    tags: ["社交支付", "UX", "体验设计"],
    cover: "/covers/weixin-treat.jpg?v=3",
    excerpt: "一次把「开口尴尬」变成「请客像发邀请」的社交支付全链路探索。",
    description:
      "围绕「如何让用户在社交关系中自然发起请客行为」做体验设计：快捷输入、情绪化卡片包装，以及好友 / 非好友分流。把请求从压力事件改写成一份可以被转发的邀请。",
    pages: ["/work/11.jpg?v=3"],
  },
  {
    slug: "weixin-ui-spec",
    title: "微信支付 · UI规范",
    titleEn: "Atomic UI Spec",
    year: "2026",
    client: "腾讯",
    category: "product",
    tags: ["社交支付", "UI", "体验设计"],
    cover: "/covers/weixin-ui-spec.jpg",
    excerpt: "微信支付餐饮行业无忧会员UI原子层设计规范",
    description:
      "微信支付餐饮行业无忧会员UI原子层设计规范。把会员入口、转化按钮与组件状态拆成可复用的原子层，适配 390 画板并保持微信支付绿色语言一致。",
    pages: [
      "/work/weixin-ui/02.jpg",
      "/work/weixin-ui/03.jpg",
      "/work/weixin-ui/04.jpg",
      "/work/weixin-ui/05.jpg",
      "/work/weixin-ui/06.jpg",
      "/work/weixin-ui/07.jpg",
    ],
  },
  {
    slug: "have-you-walked",
    title: "Have You Walked",
    titleEn: "Outdoor AI Education",
    year: "2026",
    client: "香港理工大学",
    category: "product",
    tags: ["交互产品", "游戏化", "AI"],
    cover: "/covers/have-you-walked.jpg?v=2",
    excerpt: "面向香港中小学生的户外教育产品：步数养成、生物收集，和一条被 AI 写出来的城市路线。",
    description:
      "Have You Walked 把行走变成游戏。学生在真实街道里完成学校任务、收集像素生物，并由 AI 根据天气与课程推荐文学线或自然线。项目入选理大设计展，并获得 Capstone Funding。",
    pages: rangeSkip(12, 26, 12),
    demo: "https://tinacen.github.io/Have-you-walked-app-demo/",
  },
  {
    slug: "gardens-app",
    title: "花园里 · 产品体验",
    titleEn: "Gardens App",
    year: "2025",
    client: "浙江世纪联华",
    category: "product",
    tags: ["UI/UX", "AR", "零售"],
    cover: "/covers/gardens-app.jpg",
    excerpt: "一款结合 AR 与 AI 的鲜花 C 端应用：买花、送花、把一束花变成可以转发的礼物。",
    description:
      "「花园里」服务联华超市场景下的鲜花零售。产品覆盖选花、配送、支付与个性化数字贺卡，让线下花艺和线上社交礼物连在同一条路径里。",
    pages: rangeSkip(27, 37, 27),
  },
  {
    slug: "hibachi-home",
    title: "洛杉矶HIBACHI餐厅网页设计",
    titleEn: "Hibachi at Home",
    year: "2026",
    client: "HIBACHI at Home",
    category: "product",
    tags: ["交互设计", "网页设计", "UIUX设计"],
    cover: "/covers/hibachi-home.jpg",
    excerpt: "为洛杉矶上门日式铁板烧服务设计品牌官网，围绕服务理解、菜单选择、报价咨询和预约转化，帮用户快速判断是否适合自己的派对场景。",
    description:
      "为洛杉矶上门日式铁板烧服务设计品牌官网，围绕“服务理解—菜单选择—报价咨询—预约转化”的用户路径，重构品牌视觉、信息架构和预订体验，帮助用户快速判断服务是否适合自己的派对场景。",
    pages: [
      "/work/hibachi/01.jpg",
      "/work/hibachi/02.jpg",
      "/work/hibachi/03.jpg",
      "/work/hibachi/04.jpg",
      "/work/hibachi/05.jpg",
      "/work/hibachi/06.jpg",
      "/work/hibachi/07.jpg",
    ],
  },
  {
    slug: "soma-robotics",
    title: "SOMA · 具身机器人",
    titleEn: "Brand Website",
    year: "2026",
    client: "SOMA 具身科技",
    category: "branding",
    tags: ["品牌设计", "官网视觉", "VI"],
    cover: "/covers/soma-robotics.jpg",
    excerpt: "为具身智能创业公司搭建 SOMA Silver VI：低噪声黑白灰、信号紫，以及一套可上线的官网与物料系统。",
    description:
      "SOMA 探索机器人在真实世界中理解、学习与执行复杂任务。围绕人类行为数据、通用机器人操作与仿真评估平台，构建 SOMA Silver VI：模块化字标、超级符号、色彩与字体规范，再落到官网组件、产品页与应用物料，传达 Physical AI 基础设施的精密、克制与未来感。",
    pages: rangeSkip(80, 108, 80),
  },
  {
    slug: "gardens-brand",
    title: "花园里 · 品牌系统",
    titleEn: "Gardens Brand",
    year: "2025",
    client: "浙江世纪联华",
    category: "branding",
    tags: ["品牌设计", "包装", "物料"],
    cover: "/covers/gardens-brand.jpg",
    excerpt: "为联华 CITYLIFE 延安南路店的鲜花零售品牌，做一套更年轻、更轻盈的识别系统。",
    description:
      "花园里作为超市整体品牌升级的一部分，关键词是自由、活力、时尚。从花瓣几何标志、包装结构到户外广告与动态分镜，把「花园礼」做成可以上架、可以传播的零售语言。",
    pages: rangeSkip(39, 49, 39),
  },
  {
    slug: "weixin-visual",
    title: "微信支付 · 视觉专题",
    titleEn: "Weixin Pay Visual",
    year: "2025",
    client: "腾讯",
    category: "branding",
    tags: ["节日视觉", "VI", "物料"],
    cover: "/covers/weixin-visual.jpg",
    excerpt: "春节红包皮肤、品牌物料与收款码说明——在合规和传播力之间找平衡点。",
    description:
      "配合商务部输出红包皮肤、新春视觉，以及微信支付对公物料：吊牌、服饰、银行接入页和收款码使用说明。把绿色支付语言从屏幕延伸到手可触达的物件。",
    pages: rangeSkip(50, 60, 50),
  },
  {
    slug: "little-shasha",
    title: "金沙湖大剧院IP设计",
    titleEn: "Little ShaSha",
    year: "2023 — 2025",
    client: "大丰文化",
    category: "ai",
    tags: ["IP 设计", "3D", "AIGC"],
    cover: "/covers/little-shasha.jpg",
    excerpt: "从建筑轮廓长出来的剧院吉祥物：出没在观众席、节日庆典和主题展里。",
    description:
      "小沙沙是独立完成的杭州金沙湖大剧院 IP。造型来自剧场建筑剪影，承担迎宾、主题节庆与周边延展。从三视图到春节主题装扮，让一个角色在真实场地里持续出现。",
    pages: rangeSkip(62, 67, 62),
  },
  {
    slug: "treat-bangbang",
    title: "奖礼棒棒品牌设计",
    titleEn: "Treat BangBang",
    year: "2025",
    client: "独立项目",
    category: "ai",
    tags: ["宠物 IP", "包装", "AIGC"],
    cover: "/covers/treat-bangbang.jpg",
    excerpt: "一套给宠物的「奖礼」——把狗、猫和零食做成可以上架的角色包装。",
    description:
      "奖礼棒棒是宠物食品 IP：角色、口味系列、挂件包装与箱体延展。用圆润的 3D 角色和手绘贴纸，把功能零食讲成一份可以送出去的礼物。",
    pages: rangeSkip(68, 73, 70),
  },
  {
    slug: "aigc-films",
    title: "AIGC 创意短片",
    titleEn: "AI Short Films",
    year: "2024 — 2025",
    client: "堆友 / 时空博物馆",
    category: "ai",
    tags: ["AIGC", "短片", "叙事"],
    cover: "/covers/aigc-films.jpg",
    excerpt: "支付宝新春贺岁片、西游记时空叙事，以及入选北京电影节科技单元的中国故事。",
    description:
      "用生成式工具完成概念、镜头与后期：堆友 × 支付宝新春短片获校园赛一等奖；时空博物馆系列讲述革命、神话与丝路。作品进入 AIGC 获奖展，并亮相北京国际电影节电影科技活动。",
    pages: rangeSkip(74, 77, 75),
  },
  {
    slug: "apple-creative",
    title: "APPLE创意设计",
    titleEn: "Echo Forest",
    year: "2026",
    client: "Apple",
    category: "ai",
    tags: ["创意编程", "AI", "Apple"],
    cover: "/covers/apple-creative.jpg",
    excerpt: "Echo Forest 数字生成编程艺术——让好点子立刻看得见。",
    description:
      "面向 Apple 场景的创意编程与生成实验。Echo Forest 把点子、代码和图像接到同一条创作链上，用 AI 把抽象想法变成可以立刻看见的视觉。",
    pages: rangeSkip(109, 123, 109),
  },
];

export const heroSlides = [7, 12, 30, 45, 62, 75].map(p);

export const filters = [
  { id: "all", label: "All" },
  { id: "product", label: "UI & UX" },
  { id: "branding", label: "Branding" },
  { id: "ai", label: "AI" },
];
